step-restore-cache: &step-restore-cache
  restore_cache:
    keys:
      - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - v1-dependencies-{{ arch }}

commands:
  install:
    parameters:
      windows:
        default: false
        type: boolean
    steps:
      - node/install:
          node-version: "16.19.0"
      - when:
          condition: << parameters.windows >>
          steps:
            - run: nvm use 16.19.0
  test:
    steps:
      - run: git config --global core.autocrlf input
      - checkout
      - *step-restore-cache
      - run: npx yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: npx yarn test

version: 2.1
orbs:
  cfa: continuousauth/npm@1.0.2
  node: circleci/node@5.1.0
  win: circleci/windows@5.0.0
jobs:
  test-linux-16:
    docker:
      - image: cimg/base:stable
    steps:
      - install
      - test
  test-mac:
    macos:
      xcode: "14.0.0"
    resource_class: macos.x86.medium.gen2
    steps:
      - install
      - test
  test-windows:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - install:
          windows: true
      - test
workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test-linux-16
      - test-mac
      - test-windows
      - cfa/release:
          requires:
            - test-linux-16
            - test-mac
            - test-windows
          filters:
            branches:
              only:
                - main
          context: cfa-release
